fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    staging: "https://github.com/puppet-community/puppet-staging.git"
  symlinks:
    pg_monz: "#{source_dir}"
